#!/bin/bash
## Bash Aliases

## `ls` Aliases
alias ls='ls -gGh --color=auto --group-directories-first'
alias sl='ls -gGh --color=auto --group-directories-first'
alias l='ls -gGh --color=auto --group-directories-first'
alias ll='ls -gGh --color=auto --group-directories-first'

## This is so I don't remove anything by accident.
# alias rm='rm -i'


## `grep` Alies
alias grep='grep --color=auto'

## Neovim Alias 
alias vim='nvim'


# Git Aliases
alias pullgit='for i in */.git/; do (cd $i/..; pwd; git pull --recurse); done;'
alias pushgit='git add .; git commit -m "auto-commit"; git push;'

alias notes='touch `date +"%m-%d-%y"`.md && vim `date +"%m-%d-%y"`.md'
