#!/bin/bash

# `import-list` contains the list of the files that I want to import.


# Get the current script diectory.
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


# Name of files that are to be imported into the existing bash session
files=("aliases-config")

for file in ${files[@]}; do
[ -f $SCRIPT_DIR/$file ] && . $SCRIPT_DIR/$file
done





